{"name": "verify that user can sign in using Id and Password", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104e70500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x0000000104e68890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x0000000104a78538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x0000000104abc878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x0000000104af6b7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x0000000104ab1374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x0000000104ab1fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x0000000104e37d2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000104e3c530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000104e1ce08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000104e3ce00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000104e0df94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x0000000104e5962c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x0000000104e597ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x0000000104e68530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given open target main page", "status": "passed", "start": 1729191666955, "stop": 1729191674013}, {"name": "When click on sign in logo and click sign in on account page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[@data-test='accountNav-signIn']\"}\n  (Session info: chrome=129.0.6668.101); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000104e70500 cxxbridge1$str$ptr + 1917112\n1   chromedriver                        0x0000000104e68890 cxxbridge1$str$ptr + 1885256\n2   chromedriver                        0x0000000104a78538 cxxbridge1$string$len + 89424\n3   chromedriver                        0x0000000104abc878 cxxbridge1$string$len + 368784\n4   chromedriver                        0x0000000104af6b7c cxxbridge1$string$len + 607124\n5   chromedriver                        0x0000000104ab1374 cxxbridge1$string$len + 322444\n6   chromedriver                        0x0000000104ab1fc4 cxxbridge1$string$len + 325596\n7   chromedriver                        0x0000000104e37d2c cxxbridge1$str$ptr + 1685732\n8   chromedriver                        0x0000000104e3c530 cxxbridge1$str$ptr + 1704168\n9   chromedriver                        0x0000000104e1ce08 cxxbridge1$str$ptr + 1575360\n10  chromedriver                        0x0000000104e3ce00 cxxbridge1$str$ptr + 1706424\n11  chromedriver                        0x0000000104e0df94 cxxbridge1$str$ptr + 1514316\n12  chromedriver                        0x0000000104e5962c cxxbridge1$str$ptr + 1823204\n13  chromedriver                        0x0000000104e597ac cxxbridge1$str$ptr + 1823588\n14  chromedriver                        0x0000000104e68530 cxxbridge1$str$ptr + 1884392\n15  libsystem_pthread.dylib             0x0000000188fb6f94 _pthread_start + 136\n16  libsystem_pthread.dylib             0x0000000188fb1d34 thread_start + 8\n\n", "trace": "  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/main_page.py\", line 21, in sign_in_logo\n    context.app.header.click_sign_in_on_main_page()\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/header.py\", line 23, in click_sign_in_on_main_page\n    self.click(*self.CLICK_SIGNIN)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/pages/base_page.py\", line 48, in click\n    self.driver.find_element(*locator).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/chiranjivisingh/Desktop/QA/python-selenium-automation/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1729191674013, "stop": 1729191678205}, {"name": "And click on email chirank577@gmail.com and enter email address", "status": "skipped", "start": 1729191678338, "stop": 1729191678338}, {"name": "And click on password **********  enter valid password", "status": "skipped", "start": 1729191678338, "stop": 1729191678338}, {"name": "And click on sign in with password", "status": "skipped", "start": 1729191678338, "stop": 1729191678338}, {"name": "Then Verify user can sign in using valid email address and password", "status": "skipped", "start": 1729191678338, "stop": 1729191678338}], "start": 1729191665102, "stop": 1729191678338, "uuid": "85ac48ee-ddb2-4297-b199-0414148732fa", "historyId": "70c56212eb1b0c1ec26094687b9e6173", "fullName": "target main page sign in: verify that user can sign in using Id and Password", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "target main page sign in"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}